### ISSUE TITLE
Can't install properly

### ISSUE THREAD

**Issue by macrospecter** [replete/obsidian-minimal-theme-css-snippets#8]
This is likely my issue, but I can't seem to get the Separator to install. I've saved the code as a css file, along with my other snippets, in the snippets folder. And I altered this part of the code:

.nav-files-container [class*=nav-]:has(:is(
    [data-path="Folder A"],
    [data-path="Folder D"],

But no lines are showing up under those folders in the file navigator. Any idea what I might be doing incorrectly?

I'm on a Mac, Sonoma; newly updated Obsidian.

Thanks!

**Comment by replete** [comment]
I would recommend updating Obsidian (see Installer version in About > Obsidian) via the installer app. This is mentioned in the README.

When obsidian updates itself without using the installer, the chromium part of electron does not get updated, and one of the versions around 1.18 I think made `:has()` CSS features work. Without a modern version of chromium/electron (which you only get updated by running the latest installer) this can happen. I think that is most likely.

Otherwise, make a CSS class with`.nav-files-container { outline: 1px solid red }` in the same file to confirm that the CSS file is loaded at all.

**Comment by macrospecter** [comment]
Thanks for the reply. I re-updated Obsidian using the official installer (now on installer version 1.7.7). But the snippet still seems not to be working, unfortunately. I added a line to the css file that says: .nav-files-container { outline: 1px solid red }. But that didn't seem to produce a difference, either. I restarted everything and refreshed my snippets, too.

**Comment by replete** [comment]
![Screenshot 2024-12-21 at 19 30 35](https://github.com/user-attachments/assets/5642e0b2-a41a-4bdf-994b-31f9f74ea6a8)

Definitely working here. 

Is the CSS file up to date? It changed at some point after an Obsidian update.

**Comment by macrospecter** [comment]
Gosh, I'm sorry. I haven't done any snippet editing in months and completely forgot to activate the snippet. Apologies for taking up your time! It's a fabulous snippet, and now working beautifully.
